from __future__ import annotations

import argparse
import json
import re
import unicodedata
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
GUIDED_CLASS_IDS = {f"SE-{number:03d}" for number in range(1, 97)}
OUTPUT = ROOT / "curriculum.yaml"
CATALOG = ROOT / "catalog.json"

PHASE_3_TARGET_END = 180
PHASE_4_TARGET_START = 181
PHASE_4_TARGET_END = 360

STAGES = [
    ("A", "Fundamentos de la profesión"),
    ("B", "Programación y construcción"),
    ("C", "Producto, requisitos y especificación"),
    ("D", "Superficies y formas de software"),
    ("E", "Diseño, arquitectura, datos e integración"),
    ("F", "Calidad, seguridad y entrega"),
    ("G", "Operación, evolución y liderazgo"),
    ("H", "Ingeniería de software nativa con IA"),
]

# Phase 1 deliberately specifies every class title before class generation begins.
# Each part has ten core classes, one studio and one integrative project.
PARTS = [
    ("00", "A", "Ingeniería de software como profesión", "suite", [
        "Software, sistemas y productos: fronteras de la disciplina",
        "Historia de la crisis del software a la ingeniería continua",
        "Ciclo de vida completo y responsabilidades profesionales",
        "Ética, interés público y consecuencias de las decisiones técnicas",
        "Roles, especialidades y colaboración interdisciplinaria",
        "Evidencia, incertidumbre y pensamiento crítico en ingeniería",
        "Calidad interna, externa y calidad en uso",
        "Restricciones, riesgos y compromisos entre atributos",
        "Sostenibilidad, inclusión y responsabilidad social",
        "Cómo leer estándares, documentación y literatura técnica",
        "Taller: anatomía verificable de un producto real",
        "Proyecto: mapa profesional y contrato personal de aprendizaje",
    ]),
    ("01", "A", "Computadores y representación de información", "polyglot-programming-labs", [
        "Arquitectura básica de un computador moderno",
        "Bits, bytes, bases numéricas y representación",
        "Texto, Unicode, codificaciones y mojibake",
        "Enteros, coma flotante, precisión y errores numéricos",
        "CPU, instrucciones, registros y ciclos de ejecución",
        "Memoria, cachés, almacenamiento y jerarquías",
        "Procesos, hilos, interrupciones y entrada/salida",
        "Compilación, interpretación, bytecode y JIT",
        "Runtimes, máquinas virtuales y recolección de basura",
        "Rendimiento, consumo energético y límites físicos",
        "Taller: observar un programa desde el código hasta la máquina",
        "Proyecto: informe reproducible de comportamiento y recursos",
    ]),
    ("02", "A", "Sistemas operativos, terminal y automatización base", "suite", [
        "Windows, Linux, macOS y sus modelos operativos",
        "Sistemas de archivos, rutas, enlaces y metadatos",
        "Usuarios, grupos, permisos y elevación de privilegios",
        "Procesos, señales, servicios y tareas programadas",
        "Terminales, shells y composición de comandos",
        "PowerShell, Bash y portabilidad de scripts",
        "Variables de entorno, configuración y secretos",
        "Instalación de software y gestores de paquetes del sistema",
        "Logs del sistema y diagnóstico de fallos",
        "Virtualización, WSL y aislamiento local",
        "Taller: preparar y reparar un entorno reproducible",
        "Proyecto: kit de diagnóstico multiplataforma",
    ]),
    ("03", "A", "Redes, Internet y protocolos", "suite", [
        "Modelos OSI y TCP/IP como herramientas de diagnóstico",
        "Ethernet, Wi-Fi, direccionamiento y redes locales",
        "IPv4, IPv6, subredes, rutas y NAT",
        "TCP, UDP, QUIC y decisiones de transporte",
        "DNS, nombres, resolución y fallos",
        "HTTP, semántica, caché y negociación",
        "TLS, certificados y confianza en tránsito",
        "Proxies, balanceadores, gateways y CDN",
        "Sockets, conexiones persistentes y tiempo real",
        "Captura, medición y diagnóstico de tráfico",
        "Taller: seguir una petición de extremo a extremo",
        "Proyecto: servicio observable y tolerante a fallos de red",
    ]),
    ("04", "A", "Pensamiento computacional y resolución de problemas", "polyglot-programming-labs", [
        "Descomposición, abstracción y reconocimiento de patrones",
        "Lógica proposicional, predicados e inferencia",
        "Conjuntos, relaciones, funciones y grafos",
        "Invariantes, precondiciones y poscondiciones",
        "Recursión, inducción y razonamiento estructural",
        "Algoritmos, corrección y terminación",
        "Complejidad temporal y espacial",
        "Heurísticas, aproximación y límites computacionales",
        "Modelado de estado, transiciones y eventos",
        "Resolución sistemática y registro de hipótesis",
        "Taller: descomponer un problema ambiguo",
        "Proyecto: especificación y solución contrastable",
    ]),
    ("05", "B", "Fundamentos de programación", "polyglot-programming-labs", [
        "Valores, expresiones, tipos y variables",
        "Control de flujo y decisiones",
        "Iteración, recursión y recorridos",
        "Funciones, parámetros, retorno y alcance",
        "Errores, excepciones y resultados explícitos",
        "Colecciones y transformación de datos",
        "Entrada, salida y serialización",
        "Módulos, interfaces y separación de responsabilidades",
        "Pruebas tempranas y diseño por ejemplos",
        "Legibilidad, nombres y mantenimiento básico",
        "Taller: transferir una solución entre lenguajes",
        "Proyecto: herramienta de línea de comandos probada",
    ]),
    ("06", "B", "Paradigmas de programación", "polyglot-programming-labs", [
        "Programación imperativa y estado mutable",
        "Programación procedural y descomposición funcional",
        "Orientación a objetos, mensajes y encapsulación",
        "Programación funcional, composición e inmutabilidad",
        "Programación declarativa y basada en reglas",
        "Programación lógica y resolución",
        "Programación orientada a eventos",
        "Programación reactiva y flujos",
        "Programación concurrente y actores",
        "Selección y combinación responsable de paradigmas",
        "Taller: una regla de negocio en cinco paradigmas",
        "Proyecto: comparación semántica con pruebas comunes",
    ]),
    ("07", "B", "Estructuras de datos y algoritmos", "polyglot-programming-labs", [
        "Arreglos, listas y secuencias",
        "Pilas, colas, deques y prioridades",
        "Tablas hash, mapas y conjuntos",
        "Árboles, tries y estructuras jerárquicas",
        "Grafos y recorridos",
        "Búsqueda, ordenamiento y selección",
        "Algoritmos voraces y programación dinámica",
        "Backtracking, divide y vencerás",
        "Índices, probabilísticas y estructuras persistentes",
        "Complejidad empírica, benchmarks y perfiles",
        "Taller: elegir por carga y no por costumbre",
        "Proyecto: biblioteca comparada con casos límite",
    ]),
    ("08", "B", "Entornos, herramientas y depuración", "suite", [
        "Editores, IDE y servidores de lenguaje",
        "Depuradores, breakpoints y observación de estado",
        "Profilers de CPU, memoria, I/O y red",
        "Compiladores, linters, formatters y análisis estático",
        "REPL, notebooks y desarrollo exploratorio",
        "Gestores de versiones de runtimes",
        "Entornos virtuales y aislamiento de dependencias",
        "Dev Containers y entornos desechables",
        "Reproducción de errores y reducción de casos",
        "Ergonomía, accesibilidad y productividad del entorno",
        "Taller: diagnosticar un fallo desconocido",
        "Proyecto: entorno de desarrollo autocontenido",
    ]),
    ("09", "B", "Bibliotecas, paquetes, SDK y automatización", "suite", [
        "Biblioteca, framework, runtime, plataforma y SDK",
        "SemVer, compatibilidad y contratos públicos",
        "Resolución de dependencias y lockfiles",
        "Paquetes, módulos y publicación",
        "CLI, flags, configuración y códigos de salida",
        "Scripting repetible y tareas idempotentes",
        "Plugins, extensiones y puntos de integración",
        "Generación de código y metaprogramación",
        "Licencias, procedencia y reutilización",
        "Diseño de experiencia para desarrolladores",
        "Taller: empaquetar una capacidad reusable",
        "Proyecto: SDK y CLI con compatibilidad verificada",
    ]),
    ("10", "C", "Descubrimiento y estrategia de producto", "suite", [
        "Problemas, síntomas, necesidades y oportunidades",
        "Usuarios, actores, trabajos y contextos",
        "Investigación, entrevistas y evidencia cualitativa",
        "Hipótesis, supuestos y preguntas críticas",
        "Propuesta de valor y resultados deseados",
        "Segmentación, mercado y alternativas existentes",
        "Prototipos, experimentos y reducción de incertidumbre",
        "Priorización por valor, riesgo y aprendizaje",
        "Ética del descubrimiento y protección de participantes",
        "Criterios de no éxito y decisiones de abandono",
        "Taller: convertir una petición en un problema investigable",
        "Proyecto: product brief respaldado por evidencia",
    ]),
    ("11", "C", "Economía, métricas y decisiones de producto", "suite", [
        "Modelos de negocio y sostenibilidad",
        "Costos de construcción, operación y oportunidad",
        "Resultados, outputs, actividad y vanity metrics",
        "Métricas de adopción, retención y tarea útil",
        "Telemetría de producto y consentimiento",
        "Experimentos, sesgos y causalidad básica",
        "North Star, guardrails y métricas contrarias",
        "FinOps de producto y costo por resultado",
        "Portafolio, opciones y secuenciación de inversión",
        "Decisiones reversibles e irreversibles",
        "Taller: diseñar un árbol de métricas",
        "Proyecto: caso de viabilidad técnico-económica",
    ]),
    ("12", "C", "Ingeniería de requisitos", "suite", [
        "Elicitación, análisis, especificación y validación",
        "Requisitos funcionales y reglas de negocio",
        "Atributos de calidad y restricciones",
        "Casos de uso, historias y job stories",
        "Criterios de aceptación y ejemplos",
        "Priorización, dependencias y negociación",
        "Trazabilidad desde necesidad hasta evidencia",
        "Requisitos regulatorios, de datos y seguridad",
        "Gestión de cambios y líneas base",
        "Ambigüedad, contradicción e incompletitud",
        "Taller: reparar requisitos no verificables",
        "Proyecto: especificación de requisitos revisable",
    ]),
    ("13", "C", "Especificaciones, contratos y modelos", "suite", [
        "Especificación informal, semiformal y formal",
        "Specification by Example y BDD",
        "Contratos, invariantes y diseño por contrato",
        "Modelos estructurales, conductuales y de información",
        "Máquinas de estado y model checking introductorio",
        "Esquemas de datos y validación",
        "OpenAPI, AsyncAPI, GraphQL y contratos de eventos",
        "Compatibilidad, versionado y evolución de contratos",
        "Spec-first, spec-anchored y spec-as-source",
        "Especificaciones ejecutables y pruebas contractuales",
        "Taller: convertir intención en contrato comprobable",
        "Proyecto: paquete de especificaciones trazables",
    ]),
    ("14", "C", "Experiencia, accesibilidad e internacionalización", "suite", [
        "Diseño centrado en personas y tareas",
        "Arquitectura de información y navegación",
        "Interacción, affordances y retroalimentación",
        "Estados vacíos, carga, error y recuperación",
        "Accesibilidad perceptible, operable y comprensible",
        "Semántica, teclado, foco y tecnologías de asistencia",
        "Diseño visual, tipografía, color y contraste",
        "Responsive, adaptativo y preferencias del usuario",
        "Internacionalización, localización y formatos culturales",
        "Investigación de usabilidad y medición",
        "Taller: auditar y reparar un flujo excluyente",
        "Proyecto: prototipo accesible evaluado con usuarios",
    ]),
    ("15", "C", "Procesos, planificación y estimación", "suite", [
        "Modelos predictivos, iterativos e incrementales",
        "Agile como principios y no como ceremonia",
        "Scrum, Kanban, XP y Shape Up",
        "Lean, teoría de colas y límites de trabajo",
        "Estimación por tamaño, rango y evidencia histórica",
        "Planificación de entregas y gestión de dependencias",
        "Riesgos, supuestos, issues y decisiones",
        "Definition of Ready, Done y aceptación",
        "Métricas de flujo, calidad y resultados",
        "Retrospectivas y mejora del sistema de trabajo",
        "Taller: planificar bajo incertidumbre explícita",
        "Proyecto: plan adaptativo con evidencia y guardrails",
    ]),
    ("16", "C", "Git, colaboración y código abierto", "suite", [
        "Modelo de objetos y áreas de Git",
        "Commits atómicos, historial y recuperación",
        "Ramas, integración, rebase y conflictos",
        "Pull requests y revisión basada en riesgo",
        "Trunk-based, GitFlow y estrategias híbridas",
        "Issues, discusiones y trazabilidad del cambio",
        "Convenciones, ownership y CODEOWNERS",
        "Contribución, gobernanza y comunidades abiertas",
        "Licencias de software y obligaciones básicas",
        "Firmas, procedencia y protección del repositorio",
        "Taller: rescatar una integración conflictiva",
        "Proyecto: contribución revisable de extremo a extremo",
    ]),
    ("17", "C", "Documentación y conocimiento técnico", "suite", [
        "Documentación orientada a tareas y audiencias",
        "Tutoriales, how-to, referencia y explicación",
        "README, instalación y primer éxito",
        "ADRs, RFCs y registro de decisiones",
        "Diagramas, modelos y documentación visual",
        "API docs, ejemplos y contratos publicados",
        "Runbooks, playbooks y documentación operacional",
        "Docs as code, revisión y publicación",
        "Búsqueda, glosarios y arquitectura de conocimiento",
        "Documentación para humanos, máquinas y LLM",
        "Taller: reconstruir conocimiento perdido",
        "Proyecto: portal documental versionado",
    ]),
    ("18", "D", "CLI, TUI, servicios y automatización", "framework-ecosystems-labs", [
        "Diseño de interfaces de línea de comandos",
        "Entrada estándar, salida y composición por pipes",
        "Configuración, flags, archivos y precedencia",
        "Códigos de salida, errores y diagnóstico",
        "TUI, terminales y accesibilidad",
        "Daemons, servicios y ciclo de vida",
        "Schedulers, workers y trabajos por lotes",
        "Automatización idempotente y reanudable",
        "Distribución de binarios y actualizaciones",
        "Telemetría opt-in y privacidad en herramientas",
        "Taller: endurecer una automatización frágil",
        "Proyecto: herramienta operable multiplataforma",
    ]),
    ("19", "D", "Web, frontend y aplicaciones progresivas", "framework-ecosystems-labs", [
        "Plataforma web, HTML semántico y CSS",
        "JavaScript, DOM y eventos del navegador",
        "Renderizado cliente, servidor, estático e híbrido",
        "Estado, componentes y gestión de datos",
        "Formularios, validación y experiencia de error",
        "Navegación, routing y URLs durables",
        "Rendimiento web y presupuestos",
        "Seguridad del navegador y políticas de contenido",
        "PWA, caché, offline y sincronización",
        "SEO, metadatos y descubribilidad",
        "Taller: construir un flujo web resiliente",
        "Proyecto: aplicación web accesible y offline",
    ]),
    ("20", "D", "Backend, APIs y procesamiento asíncrono", "framework-ecosystems-labs", [
        "Responsabilidades y fronteras del backend",
        "REST y semántica de recursos",
        "RPC, GraphQL y selección de interfaz",
        "Validación, errores y contratos consistentes",
        "Autenticación, autorización y contexto",
        "Idempotencia, reintentos y deduplicación",
        "Jobs, colas y procesamiento diferido",
        "Archivos, streaming y cargas extensas",
        "Caching, rate limiting y protección",
        "Health, readiness y shutdown ordenado",
        "Taller: reparar una API insegura e inconsistente",
        "Proyecto: servicio contractual operable",
    ]),
    ("21", "D", "Software móvil, escritorio y multiplataforma", "framework-ecosystems-labs", [
        "Modelos de aplicación móvil y de escritorio",
        "Ciclo de vida, suspensión y reanudación",
        "Nativo, híbrido, web wrapper y cross-platform",
        "Almacenamiento local y sincronización",
        "Permisos, sensores y capacidades del dispositivo",
        "Interacción táctil, teclado, mouse y accesibilidad",
        "Actualizaciones, tiendas y distribución empresarial",
        "Offline-first y resolución de conflictos",
        "Rendimiento, batería y recursos limitados",
        "Firma, sandbox y seguridad del cliente",
        "Taller: adaptar un producto a dos plataformas",
        "Proyecto: cliente multiplataforma con sincronización",
    ]),
    ("22", "D", "Embedded, IoT y tiempo real", "framework-ecosystems-labs", [
        "Hardware, firmware y software embebido",
        "Microcontroladores, periféricos y buses",
        "Restricciones de memoria, energía y cómputo",
        "Sistemas de tiempo real y deadlines",
        "Interrupciones, concurrencia y estado compartido",
        "Protocolos IoT y conectividad intermitente",
        "Actualizaciones OTA y recuperación",
        "Identidad de dispositivo y gestión de claves",
        "Edge, gateways y procesamiento local",
        "Safety, seguridad y vida útil prolongada",
        "Taller: modelar fallos físicos y digitales",
        "Proyecto: dispositivo simulado operable y actualizable",
    ]),
    ("23", "D", "Software especializado y dominios", "suite", [
        "Software científico y reproducibilidad",
        "Ingeniería de datos y procesamiento analítico",
        "Machine learning como componente de producto",
        "Videojuegos, loops, entidades y simulación",
        "Gráficos, audio, XR y experiencias inmersivas",
        "Fintech, contabilidad e invariantes monetarias",
        "Salud, datos sensibles y sistemas regulados",
        "Blockchain, consenso y contratos inteligentes",
        "Sistemas geoespaciales y temporales",
        "Low-code, no-code y automatización visual",
        "Taller: comparar riesgos entre dominios",
        "Proyecto: diseño profundo de un dominio elegido",
    ]),
    ("24", "E", "Diseño, patrones y refactorización", "suite", [
        "Cohesión, acoplamiento y encapsulación",
        "SOLID y sus límites",
        "Composición, herencia y delegación",
        "Patrones creacionales, estructurales y conductuales",
        "Patrones funcionales, reactivos y concurrentes",
        "Code smells y diagnóstico contextual",
        "Refactorización segura apoyada por pruebas",
        "Diseño para cambio, prueba y operación",
        "Complejidad accidental y esencial",
        "Deuda técnica, interés y opciones",
        "Taller: refactorizar sin alterar comportamiento",
        "Proyecto: evolución compatible de un componente",
    ]),
    ("25", "E", "Arquitectura de software y dominio", "suite", [
        "Drivers, restricciones y atributos de arquitectura",
        "Vistas lógica, runtime, datos y despliegue",
        "Monolito, modular monolith y servicios",
        "Capas, hexagonal, clean y ports and adapters",
        "Domain-Driven Design estratégico y táctico",
        "Event-driven, CQRS y event sourcing",
        "Arquitecturas serverless, edge y peer-to-peer",
        "Fitness functions y arquitectura evolutiva",
        "Trade-offs, ADR y evaluación de alternativas",
        "Arquitectura socio-técnica y límites de equipo",
        "Taller: revisar una arquitectura contra escenarios",
        "Proyecto: arquitectura defendible y verificable",
    ]),
    ("26", "E", "Datos, persistencia y recuperación", "database-systems-labs", [
        "Modelado conceptual, lógico y físico",
        "Relacional, documental, clave-valor, grafos y series",
        "Transacciones, aislamiento y concurrencia",
        "Restricciones, invariantes y consistencia",
        "Consultas, índices y patrones de acceso",
        "Migraciones compatibles y evolución de esquema",
        "Replicación, partición y distribución",
        "Cachés y consistencia entre capas",
        "Backups, restauración y pruebas de recuperación",
        "Privacidad, retención y ciclo de vida del dato",
        "Taller: corregir una migración peligrosa",
        "Proyecto: capa de datos recuperable",
    ]),
    ("27", "E", "Integración, eventos y mensajería", "suite", [
        "Integración síncrona y asíncrona",
        "Mensajes, eventos, comandos y documentos",
        "Brokers, colas, topics y logs distribuidos",
        "Entrega, orden, duplicación y semánticas",
        "Outbox, inbox, sagas y compensación",
        "CDC, ETL, ELT y sincronización",
        "Webhooks, polling y suscripciones",
        "Compatibilidad de esquemas y registros",
        "Anti-corruption layers y traducción de modelos",
        "Observabilidad y seguridad de integraciones",
        "Taller: provocar y contener mensajes duplicados",
        "Proyecto: flujo integrado tolerante a reintentos",
    ]),
    ("28", "E", "Concurrencia y sistemas distribuidos", "suite", [
        "Concurrencia, paralelismo y asincronía",
        "Memoria compartida, locks y condiciones de carrera",
        "Actores, canales y structured concurrency",
        "Tiempo, relojes y orden parcial",
        "Fallos parciales y modelos de red",
        "Consistencia, disponibilidad y particiones",
        "Consenso, elección y coordinación",
        "Idempotencia y procesamiento distribuido",
        "Replicación, sharding y balanceo",
        "Caos controlado y pruebas de distribución",
        "Taller: reproducir una carrera y un fallo parcial",
        "Proyecto: servicio distribuido con degradación",
    ]),
    ("29", "E", "Cloud, plataforma e infraestructura", "suite", [
        "IaaS, PaaS, SaaS y responsabilidad compartida",
        "Máquinas virtuales, contenedores y aislamiento",
        "Orquestación y scheduling",
        "Serverless y ejecución gestionada",
        "Redes, identidad y secretos en cloud",
        "Infraestructura como código y estado",
        "Entornos, cuentas y separación de responsabilidades",
        "Escalado, capacidad y costos",
        "Multi-cloud, híbrido y portabilidad real",
        "Plataformas internas y golden paths",
        "Taller: desplegar y destruir un entorno seguro",
        "Proyecto: plataforma mínima reproducible",
    ]),
    ("30", "F", "Estrategia y técnicas de prueba", "suite", [
        "Calidad por riesgo y propósito de las pruebas",
        "Pruebas unitarias y diseño testable",
        "Integración, componentes y contratos",
        "End-to-end, aceptación y recorridos críticos",
        "Pruebas basadas en propiedades y modelos",
        "Mutación, fuzzing y generación de casos",
        "Dobles, virtualización y entornos de prueba",
        "Datos deterministas y gestión de fixtures",
        "Pruebas exploratorias y sesiones",
        "Flakiness, diagnóstico y mantenimiento",
        "Taller: demostrar que una prueba detecta defectos",
        "Proyecto: estrategia ejecutable por riesgo",
    ]),
    ("31", "F", "Calidad, rendimiento y resiliencia", "suite", [
        "Modelos de calidad y atributos medibles",
        "Revisión, análisis estático y quality gates",
        "Carga, estrés, picos y endurance",
        "Latencia, throughput, saturación y capacidad",
        "Perfiles, benchmarks y errores de medición",
        "Timeouts, retries, backoff y jitter",
        "Circuit breakers, bulkheads y degradación",
        "Disponibilidad, durabilidad y recuperación",
        "Compatibilidad, portabilidad e interoperabilidad",
        "Calidad de experiencia y presupuestos",
        "Taller: someter un sistema a presión controlada",
        "Proyecto: informe reproducible de calidad",
    ]),
    ("32", "F", "Seguridad, privacidad y cumplimiento", "suite", [
        "Principios de seguridad y modelos de amenaza",
        "Identidad, autenticación y sesiones",
        "Autorización, recursos y mínimo privilegio",
        "Validación, codificación y clases de inyección",
        "Criptografía aplicada y gestión de claves",
        "Secretos, configuración y separación de ambientes",
        "Privacidad por diseño y minimización",
        "Secure SDLC, abuso y pruebas negativas",
        "Vulnerabilidades, divulgación y respuesta",
        "Cumplimiento, evidencia y límites legales",
        "Taller: explotar y reparar un control aparente",
        "Proyecto: producto con seguridad verificable",
    ]),
    ("33", "F", "Build, release y cadena de suministro", "suite", [
        "Build reproducible y hermético",
        "Artefactos, repositorios y promoción",
        "Dependencias directas, transitivas y vendorización",
        "SBOM, procedencia y atestaciones",
        "Firmas, checksums y verificación",
        "Versionado, compatibilidad y changelog",
        "Feature flags y entrega progresiva",
        "Canary, blue-green y rollback",
        "Instaladores, paquetes y actualizaciones",
        "Riesgos de CI y dependencias comprometidas",
        "Taller: verificar la procedencia de un release",
        "Proyecto: release firmado y recuperable",
    ]),
    ("34", "F", "CI/CD, IaC y platform engineering", "suite", [
        "Integración continua y feedback temprano",
        "Pipelines, jobs, matrices y cachés",
        "Tests, seguridad y políticas como gates",
        "Credenciales efímeras y OIDC",
        "Entrega y despliegue continuos",
        "Infraestructura como código en pipeline",
        "GitOps y reconciliación",
        "Entornos preview y datos seguros",
        "Developer portals y capacidades de plataforma",
        "Métricas DORA y mejora sin gaming",
        "Taller: endurecer un pipeline vulnerable",
        "Proyecto: camino a producción con rollback",
    ]),
    ("35", "G", "Observabilidad, SRE e incidentes", "suite", [
        "Señales, eventos y observabilidad útil",
        "Logs estructurados y correlación",
        "Métricas, dimensiones y cardinalidad",
        "Trazas distribuidas y contexto",
        "SLI, SLO, SLA y presupuestos de error",
        "Alertas accionables y fatiga",
        "Runbooks, on-call y escalamiento",
        "Gestión de incidentes y comunicación",
        "Postmortems sin culpa y aprendizaje",
        "Continuidad, disaster recovery y ejercicios",
        "Taller: diagnosticar con telemetría incompleta",
        "Proyecto: operación observable y recuperable",
    ]),
    ("36", "G", "Mantenimiento y modernización legacy", "suite", [
        "Mantenimiento correctivo, adaptativo y perfectivo",
        "Arqueología de código y recuperación de conocimiento",
        "Pruebas de caracterización y seams",
        "Dependencias obsoletas y riesgo acumulado",
        "Strangler, branch by abstraction y anticorruption",
        "Migraciones de runtime, lenguaje y framework",
        "Migraciones de datos sin interrupción",
        "Compatibilidad, coexistencia y doble escritura",
        "Retiro, archivado y disposición de sistemas",
        "Economía de reescribir frente a evolucionar",
        "Taller: estabilizar antes de modernizar",
        "Proyecto: migración incremental reversible",
    ]),
    ("37", "G", "Gestión, liderazgo y práctica profesional", "suite", [
        "Liderazgo técnico sin autoridad formal",
        "Diseño de equipos y ownership",
        "Comunicación, facilitación y conflicto",
        "Mentoría, feedback y crecimiento",
        "Estimación organizacional y compromisos",
        "Gestión de riesgos y decisiones ejecutivas",
        "Compras, proveedores y evaluación técnica",
        "Propiedad intelectual, contratos y ética",
        "Economía del software y costo total",
        "Portafolio, entrevistas y defensa profesional",
        "Taller: conducir una revisión de decisión difícil",
        "Proyecto: dossier profesional defendible",
    ]),
    ("38", "H", "Desarrollo de software asistido por IA", "suite", [
        "Capacidades y límites de los modelos generativos",
        "Prompting, instrucciones y criterios de salida",
        "Contexto, archivos, memoria y recuperación",
        "Autocompletado, chat, edición y generación",
        "Prototipado, scaffolding y exploración de alternativas",
        "Generación de pruebas, documentación y migraciones",
        "Revisión, refactorización y explicación asistidas",
        "Context engineering y reducción de ambigüedad",
        "Evals de exactitud, utilidad, costo y latencia",
        "Privacidad, propiedad intelectual y código inseguro",
        "Taller: comparar flujos manual, asistido y automatizado",
        "Proyecto: cambio real con trazabilidad y revisión humana",
    ]),
    ("39", "H", "SPEC, agentes y ciclo de vida agentic", "suite", [
        "De la intención a la especificación durable",
        "Constitución, specify, clarify, plan y tasks",
        "Implementación, análisis y convergencia contra SPEC",
        "Greenfield, brownfield, bug fixing e idea assessment",
        "Agentes, herramientas, permisos y límites de autoridad",
        "Skills, plugins, hooks y entornos aislados",
        "MCP, recursos, prompts, tools y confianza",
        "Delegación, subagentes y sistemas multiagente",
        "Human-in-the-loop, aprobación y acciones reversibles",
        "Seguridad agentic, prompt injection y auditoría",
        "Taller: detener, recuperar y evaluar un agente",
        "Proyecto final: producto operable construido desde SPEC",
    ]),
]


def slugify(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value)
    ascii_value = normalized.encode("ascii", "ignore").decode("ascii").lower()
    return re.sub(r"[^a-z0-9]+", "-", ascii_value).strip("-")


def build_payload() -> dict:
    stage_names = dict(STAGES)
    lesson_number = 1
    parts = []
    for part_id, stage_id, title, owner, lesson_titles in PARTS:
        if len(lesson_titles) != 12:
            raise ValueError(f"Part {part_id} must define exactly 12 classes")
        part_slug = slugify(title)
        part_path = f"classes/part-{part_id}-{part_slug}"
        lessons = []
        for position, lesson_title in enumerate(lesson_titles, start=1):
            kind = "project" if position == 12 else "studio" if position == 11 else "class"
            hours = 8 if kind == "project" else 6 if kind == "studio" else 4
            lesson_id = f"SE-{lesson_number:03d}"
            lesson_slug = slugify(lesson_title)
            lessons.append({
                "id": lesson_id,
                "number": lesson_number,
                "title": lesson_title,
                "kind": kind,
                "estimated_hours": hours,
                "status": "GUIDED" if lesson_id in GUIDED_CLASS_IDS else "PLANNED",
                "path": f"{part_path}/{lesson_id.lower()}-{lesson_slug}",
            })
            lesson_number += 1
        parts.append({
            "id": part_id,
            "stage": stage_id,
            "stage_title": stage_names[stage_id],
            "title": title,
            "owner": owner,
            "path": part_path,
            "lessons": lessons,
        })
    return {
        "schema_version": 1,
        "program": "software-engineering-learning-suite",
        "language": "es",
        "baseline_date": "2026-09-30",
        "status": "PHASE_3_AND_4_REBUILDING",
        "phase_3_target": {
            "first_class": "SE-001",
            "last_class": f"SE-{PHASE_3_TARGET_END:03d}",
            "classes": PHASE_3_TARGET_END,
            "approved": len(GUIDED_CLASS_IDS),
        },
        "phase_4_target": {
            "first_class": f"SE-{PHASE_4_TARGET_START:03d}",
            "last_class": f"SE-{PHASE_4_TARGET_END:03d}",
            "classes": PHASE_4_TARGET_END - PHASE_4_TARGET_START + 1,
            "approved": 0,
        },
        "part_count": len(parts),
        "class_count": sum(len(part["lessons"]) for part in parts),
        "estimated_hours": sum(
            lesson["estimated_hours"] for part in parts for lesson in part["lessons"]
        ),
        "stages": [{"id": key, "title": value} for key, value in STAGES],
        "parts": parts,
    }


def render(payload: dict) -> str:
    # JSON is a strict subset of YAML; keeping this representation avoids a runtime
    # dependency while preserving a curriculum.yaml contract for downstream tools.
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        return path.exists() and path.read_text(encoding="utf-8") == content
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    payload = build_payload()
    class_status = Counter(
        lesson["status"] for part in payload["parts"] for lesson in part["lessons"]
    )
    catalog = {
        "program": payload["program"],
        "baseline_date": payload["baseline_date"],
        "status": payload["status"],
        "stages": len(payload["stages"]),
        "parts": payload["part_count"],
        "classes": payload["class_count"],
        "estimated_hours": payload["estimated_hours"],
        "class_status": dict(sorted(class_status.items())),
        "phase_3_target": payload["phase_3_target"],
        "phase_4_target": payload["phase_4_target"],
    }
    targets = [
        (OUTPUT, render(payload)),
        (CATALOG, json.dumps(catalog, ensure_ascii=False, indent=2) + "\n"),
    ]
    stale = [str(path.relative_to(ROOT)) for path, content in targets if not write_or_check(path, content, args.check)]
    if stale:
        print("GENERATED_FILES_STALE: " + ", ".join(stale))
        return 1
    print(f"PROGRAM_BLUEPRINT_OK: {payload['part_count']} parts, {payload['class_count']} classes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
