"""Datos editoriales curados para las cuarenta rutas profesionales.

No representan ofertas universales ni estados de madurez de las clases. Su función es
relacionar responsabilidades profesionales con partes, clases y evidencias reales del
programa sin duplicar el contenido curricular.
"""

from __future__ import annotations


SOURCES = {
    "SWEBOK": ("SWEBOK Guide v4.0a", "IEEE Computer Society", "https://www.computer.org/education/bodies-of-knowledge/software-engineering"),
    "ISO25010": ("ISO/IEC 25010:2023", "ISO", "https://www.iso.org/standard/78176.html"),
    "ISO29148": ("ISO/IEC/IEEE 29148:2018", "ISO", "https://www.iso.org/standard/72089.html"),
    "WCAG": ("Web Content Accessibility Guidelines 2.2", "W3C", "https://www.w3.org/TR/WCAG22/"),
    "I18N": ("Internationalization techniques", "W3C", "https://www.w3.org/International/techniques/"),
    "UNICODE": ("The Unicode Standard 17.0", "Unicode Consortium", "https://www.unicode.org/versions/Unicode17.0.0/"),
    "OPENAPI": ("OpenAPI Specification", "OpenAPI Initiative", "https://spec.openapis.org/oas/latest.html"),
    "ASYNCAPI": ("AsyncAPI Specification", "AsyncAPI Initiative", "https://www.asyncapi.com/docs/reference/specification/latest"),
    "RFC9110": ("HTTP Semantics", "IETF", "https://www.rfc-editor.org/rfc/rfc9110"),
    "POSTGRESQL": ("PostgreSQL Documentation", "PostgreSQL Global Development Group", "https://www.postgresql.org/docs/current/"),
    "RAFT": ("In Search of an Understandable Consensus Algorithm", "Diego Ongaro y John Ousterhout", "https://raft.github.io/raft.pdf"),
    "KUBERNETES": ("Kubernetes Documentation", "CNCF / Kubernetes", "https://kubernetes.io/docs/"),
    "TERRAFORM": ("Terraform language documentation", "HashiCorp", "https://developer.hashicorp.com/terraform/language"),
    "NISTSSDF": ("Secure Software Development Framework SP 800-218", "NIST", "https://csrc.nist.gov/pubs/sp/800/218/final"),
    "SLSA": ("SLSA specification v1.2", "OpenSSF", "https://slsa.dev/spec/v1.2/"),
    "SPDX": ("SPDX Specification", "Linux Foundation", "https://spdx.dev/use/specifications/"),
    "SRE": ("Site Reliability Engineering", "Google", "https://sre.google/books/"),
    "OTEL": ("OpenTelemetry Documentation", "CNCF / OpenTelemetry", "https://opentelemetry.io/docs/"),
    "DORA": ("DORA software delivery performance metrics", "Google Cloud", "https://dora.dev/guides/dora-metrics/"),
    "GSF": ("Software Carbon Intensity Specification", "Green Software Foundation", "https://greensoftware.foundation/standards/sci/"),
    "ACMETHICS": ("ACM Code of Ethics and Professional Conduct", "ACM", "https://www.acm.org/code-of-ethics"),
    "SEMVER": ("Semantic Versioning 2.0.0", "Semantic Versioning project", "https://semver.org/spec/v2.0.0.html"),
    "GIT": ("Git Documentation", "Git project", "https://git-scm.com/docs"),
    "GITHUB": ("Collaborating with pull requests", "GitHub", "https://docs.github.com/pull-requests/collaborating-with-pull-requests"),
    "C4": ("C4 model", "Simon Brown", "https://c4model.com/"),
    "KANBAN": ("The Kanban Guide", "Kanban Guide authors", "https://kanbanguides.org/english/"),
    "DIATAXIS": ("Diátaxis documentation framework", "Diátaxis", "https://diataxis.fr/"),
    "NISTAI": ("AI Risk Management Framework", "NIST", "https://www.nist.gov/itl/ai-risk-management-framework"),
    "MCP": ("Model Context Protocol", "MCP maintainers", "https://modelcontextprotocol.io/specification/"),
    "DEVCONTAINERS": ("Development Container Specification", "Dev Container Specification maintainers", "https://containers.dev/implementors/spec/"),
    "WINDOWS": ("Windows developer documentation", "Microsoft", "https://learn.microsoft.com/windows/"),
    "POSIX": ("The Open Group Base Specifications, Issue 8", "The Open Group / IEEE", "https://pubs.opengroup.org/onlinepubs/9799919799/"),
    "FREERTOS": ("FreeRTOS Documentation", "FreeRTOS project", "https://www.freertos.org/Documentation/RTOS_book.html"),
    "ZEPHYR": ("Zephyr Project Documentation", "Zephyr Project", "https://docs.zephyrproject.org/latest/"),
}

PART_CONTEXT = {
    "00": ("criterio profesional, ética y lectura de evidencia", "contrato de responsabilidad y límites"),
    "01": ("máquina, memoria, representación y coste físico", "experimento reproducible de recursos"),
    "02": ("sistemas operativos, automatización y diagnóstico", "kit de preparación y recuperación"),
    "03": ("redes, protocolos y fallos de comunicación", "traza de una petición bajo fallos"),
    "04": ("invariantes, complejidad y resolución sistemática", "especificación contrastable"),
    "05": ("programación modular, errores y pruebas tempranas", "herramienta probada y mantenible"),
    "06": ("paradigmas y semánticas alternativas", "comparación razonada de implementaciones"),
    "07": ("estructuras, algoritmos y medición empírica", "benchmark con selección justificada"),
    "08": ("depuración, profiling y reproducción de fallos", "expediente de causa raíz"),
    "09": ("paquetes, SDK, dependencias y compatibilidad", "paquete versionado y consumible"),
    "10": ("discovery, usuarios, hipótesis y valor", "dossier de problema y decisión"),
    "11": ("economía, métricas y experimentación", "caso económico con sensibilidad"),
    "12": ("requisitos, restricciones y trazabilidad", "baseline de requisitos revisable"),
    "13": ("contratos, modelos e invariantes verificables", "especificación trazable"),
    "14": ("experiencia, accesibilidad e internacionalización", "flujo inclusivo evaluado"),
    "15": ("flujo, estimación y planificación incierta", "plan probabilístico adaptable"),
    "16": ("Git, revisión, ownership y colaboración abierta", "contribución completa y auditable"),
    "17": ("documentación, decisiones y conocimiento operativo", "paquete documental probado por terceros"),
    "18": ("interfaces de automatización y procesos durables", "herramienta operable e idempotente"),
    "19": ("plataforma web, estado y experiencia cliente", "aplicación accesible y observable"),
    "20": ("servicios, APIs y procesamiento asíncrono", "servicio contractual operable"),
    "21": ("clientes, sincronización y distribución", "cliente offline con actualización segura"),
    "22": ("firmware, tiempo real, OTA y dispositivo", "sistema simulado recuperable"),
    "23": ("dominios especializados, regulación y safety", "análisis de riesgo de dominio"),
    "24": ("diseño, patrones y refactorización segura", "evolución compatible protegida por pruebas"),
    "25": ("arquitectura, dominio y atributos de calidad", "arquitectura defendible con ADR"),
    "26": ("persistencia, transacciones y recuperación", "capa de datos restaurable"),
    "27": ("eventos, mensajería y compatibilidad", "flujo tolerante a duplicados"),
    "28": ("concurrencia, coordinación y fallos parciales", "experimento distribuido de degradación"),
    "29": ("cloud, infraestructura y plataformas", "entorno reproducible y eliminable"),
    "30": ("estrategia de pruebas guiada por riesgo", "suite que demuestra detección de defectos"),
    "31": ("calidad, rendimiento y resiliencia", "informe medido y game day"),
    "32": ("seguridad, privacidad y cumplimiento", "controles con pruebas y evidencia"),
    "33": ("build, release y cadena de suministro", "release firmado y verificable"),
    "34": ("CI/CD, IaC, plataforma y DevEx", "camino autoservicio con rollback"),
    "35": ("observabilidad, SRE e incidentes", "incidente diagnosticado y recuperado"),
    "36": ("mantenimiento, modernización y retiro", "migración incremental reversible"),
    "37": ("liderazgo, organización y decisiones", "propuesta defendida ante conflicto"),
    "38": ("ingeniería asistida por IA y evaluaciones", "cambio asistido con trazabilidad"),
    "39": ("SPEC, agentes, herramientas y guardrails", "flujo agentic controlado"),
}


def profile(
    family: str,
    level: str,
    core: str,
    flow: str,
    decisions: str,
    metrics: str,
    scenario: str,
    project: str,
    sources: str,
    adjacent: str,
) -> dict[str, object]:
    """Convierte una notación compacta en datos fáciles de validar y renderizar."""

    part_map: dict[str, list[str]] = {}
    for item in core.split(";"):
        part, ids = item.split(":", 1)
        part_map[part] = [f"SE-{int(value):03d}" for value in ids.split(",")]
    return {
        "family": family,
        "level": level,
        "core": part_map,
        "flow": flow.split("|"),
        "decisions": [tuple(item.split("|")) for item in decisions.split(";")],
        "metrics": [tuple(item.split("|")) for item in metrics.split(";")],
        "scenario": tuple(scenario.split("|")),
        "project": tuple(project.split("|")),
        "sources": sources.split("|"),
        "adjacent": adjacent.split("|"),
    }


PROFILES = {
    "software-engineer.md": profile(
        "Ingeniería general", "fundamentos → senior", "05:68,69,70;24:289,295,296;30:361,363,371;35:421,428,430",
        "Comprender|Diseñar|Construir|Verificar|Evolucionar",
        "Velocidad o mantenibilidad|hacer explícito el coste futuro y la reversibilidad|medir cambio seguro y deuda residual;Abstracción o simplicidad|introducir una capa sólo cuando elimina duplicación conceptual|probar que reduce acoplamiento sin ocultar el dominio;Entrega o estabilidad|graduar riesgo por tamaño impacto y recuperación|observar fallos y demostrar rollback",
        "Tiempo de ciclo|rapidez desde intención hasta evidencia|optimizar velocidad ignorando calidad;Defectos escapados|riesgo que llega a usuarios u operación|contar bugs sin severidad ni exposición;Tiempo de recuperación|capacidad para restaurar servicio y aprendizaje|celebrar promedios que ocultan incidentes largos",
        "Cambio pequeño que rompe un flujo vecino|una modificación aparentemente local produce errores en otro módulo|reconstruir dependencias invariantes y contrato afectado|contener revertir y añadir una prueba que reproduzca el fallo",
        "Producto vertical operable|entregar una capacidad desde requisito hasta operación y mantenimiento|código contrato pruebas ADR telemetría runbook y retrospectiva",
        "SWEBOK|ISO25010|ACMETHICS", "backend-engineer.md|qa-test-engineer.md|technical-leadership.md",
    ),
    "systems-programmer.md": profile(
        "Ingeniería general", "semi-senior → principal", "01:17,18,19;02:26,28,33;28:337,338,339;31:376,377,380",
        "Modelo de máquina|Recursos|Concurrencia|Medición|Recuperación",
        "Rendimiento o seguridad|evitar optimizaciones que rompen memoria aislamiento o portabilidad|benchmark y pruebas de sanitización;Bloqueo o progreso|elegir exclusión sincronización o diseño sin estado según garantías|reproducir carreras y demostrar ausencia de deadlock;Portabilidad o especialización|aislar dependencias de plataforma detrás de contratos|ejecutar el mismo comportamiento en entornos declarados",
        "CPU y memoria por operación|coste físico de una unidad funcional|medir sólo un promedio caliente;Latencia de cola|contención y scheduling bajo carga|culpar al runtime sin perfil;Errores de recursos|handles memoria descriptores o threads agotados|reiniciar sin localizar la fuga",
        "Proceso que se degrada hasta bloquear el host|crecen memoria hilos y latencia sin error único|capturar perfil dumps límites y secuencia temporal|liberar recursos aplicar backpressure y probar estabilidad prolongada",
        "Servicio de sistema portable|construir un proceso concurrente observable con límites de recursos|binario reproducible perfiles pruebas de carrera matriz multi-OS y procedimiento de recuperación",
        "POSIX|ISO25010|SWEBOK", "performance-engineer.md|embedded-iot-engineer.md|distributed-systems-engineer.md",
    ),
    "backend-engineer.md": profile(
        "Producto digital", "junior → principal", "20:241,246,250;26:315,318,321;27:328,329,334;35:421,425,431",
        "Regla de negocio|Contrato|Persistencia|Telemetría|Evolución",
        "Síncrono o asíncrono|evaluar latencia acoplamiento confirmación y reintentos|prueba contractual más experimento de duplicación;Consistencia o disponibilidad|declarar qué invariantes no se negocian durante particiones|historial de operaciones y reconciliación verificable;Monolito o servicio|separar por límites y autonomía reales no por moda|ADR con costes de operación y estrategia de retorno",
        "Errores por operación|corrección observada por contrato y tipo de fallo|mezclar validación con dependencia caída;Latencia p50 p95 p99|distribución y cola bajo carga conocida|publicar percentiles sin volumen ni ventana;Duplicados reconciliados|eficacia de idempotencia y deduplicación|ocultar el problema descartando mensajes",
        "Cobro o comando aplicado dos veces|un cliente reintenta después de perder la respuesta|correlacionar request key transacción outbox y efectos externos|contener compensar y probar que el mismo intento conserva el invariante",
        "Servicio contractual recuperable|operar una capacidad de negocio bajo reintentos degradación y migración|OpenAPI migración compatible pruebas de contrato dashboard SLO y runbook",
        "OPENAPI|RFC9110|SRE", "api-engineer.md|data-engineer.md|distributed-systems-engineer.md",
    ),
    "frontend-engineer.md": profile(
        "Producto digital", "junior → principal", "14:172,174,176;19:229,232,235;30:364,369,370;31:373,382,384",
        "Tarea de usuario|Estado|Interacción|Medición|Recuperación",
        "Renderizado cliente o servidor|comparar tiempo de interacción caché complejidad y SEO|presupuesto medido en una ruta real;Estado local o compartido|colocar cada dato donde tenga propietario y ciclo de vida claro|pruebas de transición y recuperación;Componente propio o dependencia|evaluar accesibilidad peso mantenimiento y contrato|auditoría de bundle y prueba con teclado",
        "Éxito de tarea|personas que completan el flujo sin asistencia|confundir clics con valor;Core Web Vitals por ruta|experiencia real de carga respuesta y estabilidad|optimizar laboratorio ignorando dispositivos;Errores recuperables|fallos que ofrecen salida y preservan trabajo|contar sólo excepciones JavaScript",
        "Formulario pierde información al fallar la red|la petición expira y el estado visual diverge del servidor|reproducir navegación foco caché y reintento en una sesión|preservar entrada explicar estado y verificar recuperación accesible",
        "Flujo web inclusivo y resiliente|construir una tarea completa que funcione con red degradada teclado y distintos tamaños|aplicación presupuesto de rendimiento pruebas por capas auditoría accesible y telemetría cliente",
        "WCAG|RFC9110|ISO25010", "accessibility-engineer.md|full-stack-engineer.md|performance-engineer.md",
    ),
    "full-stack-engineer.md": profile(
        "Producto digital", "junior → senior", "19:232,233,239;20:244,246,250;26:313,318,321;34:409,413,420",
        "Experiencia|Contrato|Dominio|Entrega|Operación",
        "Validar en cliente o servidor|usar cliente para feedback y servidor para autoridad|pruebas negativas en ambos límites;Consulta directa o API|proteger invariantes y evolución sin capas ceremoniales|contrato más perfil de una ruta vertical;Generalismo o profundidad|asumir una capacidad completa y pedir revisión experta donde el riesgo lo exige|evidencia de coordinación y límites documentados",
        "Tiempo de una tarea completa|latencia percibida entre interfaz API y datos|optimizar una capa aislada;Fallos por despliegue|regresiones que atraviesan contratos|atribuir todo al último commit;Cobertura de flujo crítico|protección real de la ruta de negocio|sumar cobertura de líneas sin escenarios",
        "Despliegue cambia el esquema y rompe clientes antiguos|frontend backend y base quedan temporalmente en versiones distintas|seguir contrato migración flags y orden de rollout|restaurar compatibilidad y ensayar expansión migración y contracción",
        "Fragmento vertical de producto|entregar una tarea accesible con API datos pipeline y observabilidad|UI contrato servicio migración suites de riesgo despliegue gradual y runbook",
        "OPENAPI|WCAG|DORA", "frontend-engineer.md|backend-engineer.md|software-engineer.md",
    ),
    "mobile-engineer.md": profile(
        "Clientes", "junior → principal", "14:173,176,177;21:254,256,260;30:364,367,370;33:403,405,408",
        "Ciclo de vida|Estado local|Sincronización|Distribución|Aprendizaje",
        "Nativo o multiplataforma|comparar capacidad dispositivo rendimiento equipo y vida útil|prototipo medido en plataformas objetivo;Offline o conexión obligatoria|definir qué tareas deben sobrevivir y cómo reconciliar|escenarios de conflicto y reloj;Actualización rápida o conservadora|equilibrar adopción compatibilidad y rollback limitado por tiendas|telemetría por versión y plan de retirada",
        "Sesiones sin crash|estabilidad por versión dispositivo y sistema|celebrar un promedio que oculta modelos afectados;Éxito de sincronización|operaciones convergentes después de desconexión|contar reintentos como éxito;Consumo por tarea|batería red y almacenamiento de una acción útil|medir sólo en emulador",
        "La aplicación reanuda con estado obsoleto y duplica una acción|el sistema suspendió el proceso durante una operación parcial|reconstruir lifecycle persistencia reloj y protocolo de idempotencia|reconciliar sin pérdida y probar suspensión cierre y actualización",
        "Cliente offline-first distribuible|resolver una tarea con conectividad intermitente y actualización segura|cliente sincronización conflicto accesibilidad telemetría matriz de dispositivos y plan de rollback",
        "WCAG|ISO25010|SEMVER", "frontend-engineer.md|desktop-engineer.md|backend-engineer.md",
    ),
    "desktop-engineer.md": profile(
        "Clientes", "junior → principal", "02:25,26,27;18:217,222,225;21:253,259,262;33:402,405,408",
        "Plataforma|Integración nativa|Empaquetado|Actualización|Soporte",
        "Nativo o cross-platform|comparar integración accesibilidad tamaño y mantenimiento|matriz funcional por sistema operativo;Autoactualización o control administrado|respetar permisos canales empresariales y reversión|instalación limpia upgrade downgrade y desinstalación;Privilegio o comodidad|reducir superficie y elevar sólo operaciones necesarias|pruebas con usuario estándar y auditoría de permisos",
        "Éxito de instalación|instalaciones y actualizaciones completas por plataforma|ignorar instalaciones silenciosas;Fallos por versión de SO|compatibilidad real con ambientes soportados|probar sólo la máquina del equipo;Tiempo de diagnóstico|capacidad de soporte con logs y códigos útiles|añadir telemetría invasiva",
        "Actualización deja la aplicación sin arrancar|el instalador migró configuración antes de verificar el binario|revisar firma canal permisos migración y rollback|restaurar versión anterior y probar upgrade downgrade y reparación",
        "Aplicación de escritorio mantenible|distribuir una herramienta accesible con integración nativa y actualización recuperable|paquetes firmados matriz multi-OS migración telemetría opt-in y runbook de soporte",
        "WINDOWS|POSIX|SEMVER", "mobile-engineer.md|systems-programmer.md|build-release-engineer.md",
    ),
    "embedded-iot-engineer.md": profile(
        "Sistemas físicos", "semi-senior → principal", "01:17,18,22;22:267,268,271;31:376,379,380;32:385,389,393",
        "Restricción física|Deadline|Telemetría|Actualización|Recuperación",
        "Procesar en dispositivo o edge|comparar latencia energía privacidad y conectividad|presupuesto por unidad funcional;Seguridad o disponibilidad física|diseñar modos degradados sin exponer control peligroso|hazard analysis y pruebas de transición;OTA rápida o conservadora|equilibrar parcheo flota ancho de banda y brick risk|actualización A/B y recuperación ante corte",
        "Deadlines incumplidos|respuestas fuera de ventana temporal|promediar y ocultar el peor caso;Energía por ciclo|autonomía asociada a una función útil|medir sólo CPU;Flota recuperable|dispositivos que vuelven a versión sana tras fallo OTA|confundir entrega con activación",
        "Una actualización OTA interrumpida deja dispositivos en boot loop|se pierde energía después de escribir estado parcial|examinar particiones bootloader firma versión y watchdog|arrancar imagen conocida registrar causa y reintentar de forma acotada",
        "Dispositivo simulado operable|cumplir un deadline comunicar telemetría y sobrevivir una actualización fallida|firmware o simulador presupuesto temporal amenaza OTA A/B métricas y procedimiento de recuperación",
        "FREERTOS|ZEPHYR|NISTSSDF", "systems-programmer.md|safety-critical-software-engineer.md|cloud-engineer.md",
    ),
    "safety-critical-software-engineer.md": profile(
        "Sistemas críticos", "senior → principal", "04:52,54,57;13:159,161,166;23:282,283,287;30:361,365,371",
        "Hazard|Requisito|Control|Verificación|Assurance",
        "Disponibilidad o estado seguro|definir qué degradación evita daño y cuál lo incrementa|análisis de hazards más prueba de transición;Prueba o demostración formal|usar rigor proporcional a criticidad y modelo disponible|trazabilidad de propiedades supuestos y contraejemplos;Cambio o recertificación|aislar impacto y conservar evidencia de configuración|baseline revisada y análisis de regresión",
        "Cobertura de hazards|peligros con controles y pruebas trazables|contar requisitos sin severidad;Defectos de escape críticos|fallos que invalidan una garantía de seguridad|mezclar incidentes menores y catastróficos;Tiempo hasta estado seguro|capacidad de detectar y mitigar condición peligrosa|optimizar disponibilidad sobre seguridad",
        "Sensor inconsistente activa una decisión peligrosa|dos entradas plausibles violan un supuesto no documentado|rastrear hazard requisito invariante modelo y evidencia de prueba|pasar a estado seguro aislar entrada y revisar el argumento de assurance",
        "Caso de assurance trazable|demostrar cómo un hazard se convierte en requisito control prueba y evidencia|modelo de estados invariantes matriz de trazabilidad pruebas negativas y revisión independiente",
        "ISO25010|ACMETHICS|SWEBOK", "embedded-iot-engineer.md|requirements-engineer.md|compliance-engineer.md",
    ),
    "api-engineer.md": profile(
        "Interfaces", "semi-senior → principal", "13:163,164,166;20:242,243,246;27:331,332,334;30:363,364,371",
        "Consumidor|Contrato|Compatibilidad|Gobierno|Retiro",
        "REST RPC o eventos|elegir semántica por interacción acoplamiento y tooling|prototipo contractual y escenario de fallo;Versión nueva o evolución compatible|preferir cambios aditivos con deprecación observable|consumer contract y análisis de uso;Gateway o lógica distribuida|centralizar capacidades transversales sin ocultar dominio|políticas versionadas y trazas extremo a extremo",
        "Éxito por operación|resultado contractual no sólo código HTTP|agrupar errores de cliente y servidor;Adopción de versión|consumidores migrados antes de retiro|medir llamadas sin identificar dependencia;Incidentes de compatibilidad|rupturas causadas por cambio de contrato|culpar consumidores sin test previo",
        "Un cambio opcional rompe un consumidor generado|la forma del esquema cambió aunque el endpoint conserve URL|comparar especificaciones SDK serialización y pruebas de consumidores|restaurar compatibilidad publicar deprecación y añadir contract test",
        "API gobernada de extremo a extremo|diseñar publicar observar evolucionar y retirar un contrato consumible|OpenAPI o AsyncAPI SDK ejemplos pruebas contractuales métricas de adopción y política de deprecación",
        "OPENAPI|ASYNCAPI|RFC9110", "backend-engineer.md|technical-writer.md|solutions-architect.md",
    ),
    "data-engineer.md": profile(
        "Datos", "semi-senior → principal", "26:313,318,322;27:330,332,334;29:354,356,360;35:421,423,430",
        "Fuente|Contrato de datos|Transformación|Calidad|Consumo",
        "Batch o streaming|comparar frescura coste complejidad y corrección|SLO de dato y replay controlado;Esquema central o evolución distribuida|asignar ownership y compatibilidad por productor|registro de esquemas y contract test;Recalcular o corregir en sitio|preservar lineage reproducibilidad y auditoría|backfill ensayado con reconciliación",
        "Frescura del dato|retraso desde evento hasta consumo útil|medir reloj de pipeline sin reloj de fuente;Calidad por regla|completitud validez unicidad y coherencia contextual|crear un score único sin impacto;Costo por unidad procesada|eficiencia por volumen y nivel de servicio|reducir costo degradando confiabilidad",
        "Un backfill duplica agregados y cambia métricas históricas|el job no distingue evento nuevo de reproducción|rastrear lineage claves ventanas esquema y checkpoints|aislar partición recomputar de forma idempotente y reconciliar consumidores",
        "Producto de datos trazable|publicar un dataset con contrato calidad lineage replay y coste visible|pipeline contrato pruebas de calidad backfill dashboard y runbook",
        "POSTGRESQL|ASYNCAPI|ISO25010", "database-reliability-engineer.md|distributed-systems-engineer.md|finops-engineer.md",
    ),
    "database-reliability-engineer.md": profile(
        "Datos", "senior → principal", "26:315,317,321;31:375,376,380;35:423,426,430;36:436,439,440",
        "Carga|Capacidad|Cambio|Respaldo|Restauración",
        "Índice o coste de escritura|equilibrar patrón de acceso espacio y mantenimiento|plan real más benchmark comparable;Disponibilidad o consistencia|definir garantía por operación y modo degradado|prueba de failover y reconciliación;Migrar en línea o ventana|comparar doble escritura lock impacto y reversión|ensayo sobre volumen representativo",
        "Saturación por recurso|CPU I/O locks conexiones y almacenamiento|mirar sólo CPU;Lag de réplica|riesgo de lectura obsoleta y pérdida ante failover|promediar entre réplicas;Restore time observado|tiempo real para recuperar una copia válida|confundir backup exitoso con restauración",
        "La base acepta tráfico pero las operaciones se acumulan|un cambio de consulta provoca locks y agota conexiones|correlacionar espera plan índice pool replica y despliegue|limitar carga cancelar trabajo dañino restaurar capacidad y verificar datos",
        "Base de datos recuperable bajo cambio|migrar una carga realista sin interrupción y demostrar restauración|modelo índices benchmark migración compatible backup restore telemetría y runbook",
        "POSTGRESQL|SRE|ISO25010", "data-engineer.md|site-reliability-engineer.md|legacy-modernization-engineer.md",
    ),
    "distributed-systems-engineer.md": profile(
        "Distribución", "senior → principal", "27:328,329,332;28:340,341,343;31:378,379,380;35:424,425,431",
        "Garantía|Partición|Coordinación|Degradación|Reconciliación",
        "Consistencia o disponibilidad|definir operación por operación durante partición|historial verificable y modelo de fallos;Consenso o coordinación local|pagar consenso sólo por invariantes globales necesarias|simulación de pérdida líder y split brain;Retry o fail-fast|acotar por presupuesto temporal idempotencia y carga|experimento de tormenta de reintentos",
        "Violaciones de invariante|estados imposibles observados entre nodos|contar sólo errores de transporte;Tiempo de convergencia|duración hasta acuerdo después de una partición|ocultar colas y reloj;Amplificación de reintentos|trabajo adicional causado por recuperación|medir tasa de solicitudes externas solamente",
        "Dos líderes aceptan escrituras incompatibles|una partición y relojes divergentes rompen el supuesto de unicidad|reconstruir términos quórum fencing orden y persistencia|detener escrituras inseguras elegir autoridad y reconciliar con evidencia",
        "Servicio distribuido con garantías explícitas|someter coordinación y replicación a latencia partición reinicio y duplicación|modelo de fallos protocolo pruebas de caos trazas invariantes y plan de reconciliación",
        "RAFT|SRE|OTEL", "backend-engineer.md|database-reliability-engineer.md|software-architect.md",
    ),
    "qa-test-engineer.md": profile(
        "Calidad", "junior → principal", "12:147,149,154;13:158,166,167;30:361,365,371;31:373,374,384",
        "Riesgo|Oráculo|Diseño de prueba|Ejecución|Aprendizaje",
        "Automatizar o explorar|automatizar repetición estable y explorar incertidumbre nueva|charter más regresión que captura el hallazgo;Mock o sistema real|elegir aislamiento según el riesgo contractual|test que falla ante defecto intencional;Cobertura o señal|usar métricas como pistas y no equivalentes de confianza|mutation o fault injection proporcional",
        "Defectos detectados antes de producción|capacidad de encontrar riesgo relevante temprano|premiar cantidad de casos;Flakiness|pruebas no deterministas que erosionan feedback|reintentar hasta verde;Tiempo hasta diagnóstico|velocidad para convertir fallo en causa accionable|optimizar sólo duración de suite",
        "La suite pasa pero el flujo crítico falla en producción|los tests verifican implementación aislada y no contrato ni datos reales|mapear riesgo oráculos dobles fixtures ambiente y cobertura de interacción|reproducir con el nivel mínimo adecuado y demostrar que la nueva prueba detecta el defecto",
        "Estrategia de prueba por riesgo|proteger un recorrido crítico con técnicas complementarias y límites explícitos|mapa de riesgos suites por nivel sesión exploratoria mutation informe de huecos y quality gate",
        "ISO25010|SWEBOK|NISTSSDF", "software-engineer.md|performance-engineer.md|accessibility-engineer.md",
    ),
    "performance-engineer.md": profile(
        "Calidad", "semi-senior → principal", "01:18,22,24;07:94,95,96;31:375,376,377;35:423,426,431",
        "Carga|Medición|Perfil|Cambio|Capacidad",
        "Latencia o throughput|definir objetivo y saturación según la tarea de negocio|curva de carga con percentiles;Optimizar código o arquitectura|localizar primero el recurso limitante y la cola|perfil antes y después con intervalo;Escalar o reducir demanda|comparar coste cache backpressure y degradación|prueba de capacidad con presupuesto",
        "p50 p95 p99|distribución de latencia por operación y carga|publicar un percentil sin muestra;Utilización y saturación|recurso ocupado y trabajo en espera|confundir alta utilización con problema;Costo por transacción|recursos necesarios para resultado útil|abaratar degradando SLO",
        "La latencia p99 crece aunque el promedio parece estable|una cola o pausa periódica afecta una minoría crítica|controlar carga warmup GC I/O locks red y cardinalidad|aislar cuello aplicar cambio mínimo y repetir experimento comparable",
        "Informe de capacidad reproducible|establecer baseline encontrar cuello y defender una mejora sin mover el problema|generador de carga dataset perfiles gráficos presupuesto modelo de capacidad y límites",
        "ISO25010|OTEL|SRE", "site-reliability-engineer.md|systems-programmer.md|finops-engineer.md",
    ),
    "accessibility-engineer.md": profile(
        "Inclusión", "semi-senior → lead", "14:173,174,179;19:229,233,239;21:258,263,264;30:364,369,371",
        "Tarea|Barrera|Patrón accesible|Prueba|Prevención",
        "Semántica nativa o ARIA|usar el mecanismo más interoperable y simple|matriz navegador tecnología asistiva;Automático o manual|combinar detección rápida con evaluación de tarea y comprensión|evidencia de teclado lector zoom y contraste;Conformidad o usabilidad|cumplir criterios sin perder el objetivo real de la persona|prueba de tarea con barreras priorizadas",
        "Éxito de tarea asistida|personas que completan el flujo con distintas técnicas|contar issues cerrados;Regresiones por componente|barreras reintroducidas en patrones compartidos|medir páginas y no sistema de diseño;Tiempo de remediación|velocidad desde barrera confirmada hasta solución verificada|cerrar tickets sin revalidación",
        "Un modal visible deja el foco detrás y atrapa a un lector|la implementación cambia apariencia sin gestionar nombre foco y retorno|recorrer DOM árbol accesible teclado anuncios y cierre|restaurar semántica probar variantes y convertir la solución en patrón",
        "Flujo inclusivo verificable|reparar una tarea completa y prevenir la misma barrera en el sistema de diseño|auditoría priorizada componente accesible pruebas manuales automatizadas y guía de adopción",
        "WCAG|ISO25010|ACMETHICS", "frontend-engineer.md|qa-test-engineer.md|technical-writer.md",
    ),
    "internationalization-engineer.md": profile(
        "Globalización", "semi-senior → lead", "01:15,16,24;14:177,178,180;19:233,234,240;21:256,260,263",
        "Dato internacional|Locale|Presentación|Localización|Verificación",
        "Almacenar o formatear|conservar representación canónica y aplicar locale en el borde|pruebas de ida y vuelta;Traducir texto o rediseñar contenido|preservar intención espacio y pluralización|pseudo-localización más revisión lingüística;Hora local o instante|distinguir evento zona calendario y regla futura|casos de DST y cambios de zona",
        "Defectos por locale|fallos funcionales y visuales asociados a configuración cultural|contar cadenas sin contexto;Cobertura de mensajes|interfaces externalizadas y traducibles|confundir extracción con calidad;Errores de tiempo y moneda|impacto de conversiones y redondeo incorrectos|probar sólo en UTC y dólares",
        "Una reserva cambia de día para ciertos usuarios|se mezcla instante UTC con fecha local y zona implícita|rastrear tipo serialización regla de zona locale y calendario|corregir modelo migrar datos afectados y añadir matrices de frontera temporal",
        "Producto preparado para múltiples culturas|hacer que una misma tarea funcione con locales scripts zonas y formatos distintos|modelo de datos catálogos pseudo-localización RTL matrices temporales y reporte de defectos",
        "I18N|UNICODE|WCAG", "frontend-engineer.md|mobile-engineer.md|accessibility-engineer.md",
    ),
    "requirements-engineer.md": profile(
        "Análisis", "junior → principal", "10:121,123,130;12:145,151,154;13:157,159,167;17:205,208,215",
        "Necesidad|Conflicto|Requisito|Criterio|Evidencia",
        "Detalle temprano o aprendizaje|especificar lo irreversible y explorar lo incierto|mapa de supuestos y criterios de abandono;Deseo o requisito|separar solución propuesta necesidad restricción y regla|trazabilidad hasta fuente y aceptación;Consenso o desacuerdo explícito|registrar conflicto propietario y decisión sin fabricar unanimidad|baseline y log de decisiones",
        "Requisitos verificables|afirmaciones con condición resultado y criterio observable|contar historias escritas;Cambios con impacto trazado|modificaciones conectadas a diseño prueba y riesgo|congelar alcance para mejorar métrica;Defectos por ambigüedad|fallos originados en interpretación divergente|culpar a implementación sin revisar lenguaje",
        "Dos stakeholders aprueban frases incompatibles|cada uno interpreta disponibilidad y recuperación de forma distinta|identificar términos cuantificadores contexto autoridad y consecuencias|facilitar escenarios medibles registrar decisión y actualizar trazabilidad",
        "Baseline defendible de requisitos|convertir un problema contradictorio en acuerdos verificables sin ocultar incertidumbre|mapa de stakeholders entrevistas modelos requisitos NFR criterios matriz de trazabilidad y change log",
        "ISO29148|SWEBOK|ACMETHICS", "technical-product-engineer.md|api-engineer.md|software-architect.md",
    ),
    "devops-engineer.md": profile(
        "Entrega", "semi-senior → principal", "29:353,354,359;33:397,400,404;34:409,412,420;35:422,428,430",
        "Commit|Artefacto|Entorno|Despliegue|Recuperación",
        "Velocidad o control|automatizar evidencia y aprobación proporcional al riesgo|lead time más change failure rate;Mutable o inmutable|promover el mismo artefacto y externalizar configuración|checksum entre entornos;Centralizar o autoservicio|crear paved road sin bloquear casos excepcionales|adopción tiempo de feedback y salida documentada",
        "Lead time verificable|tiempo desde cambio aceptado hasta valor desplegado|medir desde un punto conveniente;Change failure rate|cambios que exigen remediación o rollback|ocultar hotfix como éxito;Tiempo de recuperación|capacidad de revertir o corregir con evidencia|medir sólo incidentes simples",
        "Pipeline verde despliega configuración inválida|los checks validan sintaxis pero no comportamiento del entorno|seguir artefacto identidad configuración policy y señal posterior|detener promoción revertir conservar evidencia y añadir validación del fallo",
        "Camino de entrega reversible|llevar un artefacto firmado por varios entornos sin reconstrucción y recuperar un fallo|pipeline IaC OIDC SBOM promoción canary rollback observabilidad y runbook",
        "DORA|SLSA|TERRAFORM", "build-release-engineer.md|platform-engineer.md|site-reliability-engineer.md",
    ),
    "build-release-engineer.md": profile(
        "Entrega", "semi-senior → principal", "09:110,111,112;16:194,197,202;33:397,400,407;34:409,410,419",
        "Fuente|Build hermético|Artefacto|Firma|Promoción",
        "Reproducibilidad o velocidad|controlar entradas y cachés sin perder trazabilidad|rebuild independiente con mismo resultado;Versión automática o deliberada|derivar SemVer de compatibilidad y política de producto|pruebas de consumidor más changelog;Disponibilidad o cuarentena|publicar rápido sin promover artefacto no verificado|repositorios separados y atestación",
        "Builds reproducibles|resultados equivalentes desde entradas declaradas|aceptar sólo que compiló;Tiempo de pipeline|feedback y capacidad de release|acelerar quitando controles críticos;Artefactos verificables|paquetes con checksum firma SBOM y procedencia|generar evidencia que nadie comprueba",
        "Un release no puede reconstruirse tras una vulnerabilidad|dependencias y herramientas flotantes cambiaron desde el tag|inventariar fuente lockfiles builder entorno y caché|aislar artefacto fijar entradas reconstruir comparar y documentar diferencia",
        "Release verificable y recuperable|producir promover verificar y retirar un artefacto sin ambigüedad|build hermético paquete SBOM firma atestación changelog canales y rollback",
        "SLSA|SPDX|SEMVER", "devops-engineer.md|security-engineer.md|desktop-engineer.md",
    ),
    "cloud-engineer.md": profile(
        "Cloud", "semi-senior → principal", "29:349,353,354;32:387,390,393;34:412,414,415;35:425,426,430",
        "Cuenta|Identidad|Infraestructura|Servicio|Recuperación",
        "Gestionado o autogestionado|comparar control carga operativa lock-in y recuperación|TCO más prueba de salida;Una cuenta o separación|aislar riesgo blast radius facturación y deberes|policy y ejercicio de credenciales;Multi-cloud o profundidad|exigir necesidad de negocio antes de duplicar complejidad|escenario de continuidad y costes reales",
        "Cambios fuera de IaC|drift que rompe reproducibilidad y control|medir sólo recursos importados;Costo por servicio|consumo asociado a outcome y capacidad|premiar ahorro que reduce resiliencia;Recuperación por región|RTO y RPO observados ante pérdida|aceptar arquitectura en papel",
        "Una credencial comprometida modifica infraestructura crítica|un principal de CI tiene permisos y duración excesivos|rastrear identidad sesión policy cloud trail estado y recursos|revocar contener reconciliar IaC rotar confianza y verificar impacto",
        "Entorno cloud mínimo seguro|crear y destruir una plataforma con identidad efímera separación y recuperación|IaC policy OIDC estimación de coste despliegue multi-entorno alertas y ejercicio de restauración",
        "KUBERNETES|TERRAFORM|NISTSSDF", "devops-engineer.md|platform-engineer.md|security-engineer.md",
    ),
    "site-reliability-engineer.md": profile(
        "Confiabilidad", "semi-senior → principal", "28:341,342,346;31:376,378,380;35:425,427,430;36:433,436,443",
        "Expectativa|SLI|SLO|Respuesta|Aprendizaje",
        "Confiabilidad o velocidad|usar error budget como señal de decisión compartida|SLO y tendencia de consumo;Automatizar o documentar|automatizar toil entendido y conservar ruta manual segura|horas de toil y fallo de automatización;Redundancia o simplicidad|añadir copias sólo si reducen modos de fallo netos|game day y coste operativo",
        "Cumplimiento de SLO|experiencia buena medida sobre ventana acordada|usar uptime de proceso como servicio;Consumo de error budget|ritmo y concentración del riesgo|convertirlo en castigo al equipo;Toil por guardia|trabajo manual repetitivo y automatizable|automatizar sin medir demanda",
        "Servicio responde pero incumple su tarea útil|health checks pasan mientras una dependencia devuelve datos obsoletos|comparar SLI de usuario saturación trazas dependencia y despliegues|degradar contener comunicar recuperar y revisar objetivo",
        "Servicio con confiabilidad ensayada|definir SLO observar degradación y recuperar una falla compuesta|SLI dashboard alertas runbook game day timeline postmortem y backlog priorizado",
        "SRE|OTEL|DORA", "observability-engineer.md|devops-engineer.md|database-reliability-engineer.md",
    ),
    "observability-engineer.md": profile(
        "Confiabilidad", "semi-senior → principal", "03:41,43,47;20:244,250,252;35:421,424,426;39:473,477,479",
        "Pregunta|Instrumentación|Correlación|Diagnóstico|Acción",
        "Más datos o mejor señal|capturar contexto necesario con coste cardinalidad y privacidad controlados|preguntas diagnósticas respondidas por señal;Logs métricas o trazas|combinar según evento tendencia y causalidad distribuida|escenario de investigación con presupuesto;Centralizar o federar|equilibrar consistencia ownership y acceso|SLO de plataforma y contrato de telemetría",
        "Preguntas diagnosticables|incidentes que pueden explicarse con datos disponibles|contar terabytes ingeridos;Costo por señal útil|valor diagnóstico frente a almacenamiento y procesamiento|reducir retención sin evaluar investigación;Cardinalidad controlada|dimensiones que no saturan backend ni presupuesto|bloquear etiquetas útiles de forma global",
        "Una petición lenta cruza servicios sin identificador común|cada componente registra tiempo pero no conserva contexto|seguir propagación sampling reloj atributos y límites de privacidad|restaurar correlación capturar evidencia mínima y añadir contrato de instrumentación",
        "Plataforma de diagnóstico interoperable|responder preguntas de fallo sin depender de dashboards preconstruidos|convenciones OTel collector logs métricas trazas presupuesto de cardinalidad y guía de instrumentación",
        "OTEL|SRE|ISO25010", "site-reliability-engineer.md|performance-engineer.md|platform-engineer.md",
    ),
    "platform-engineer.md": profile(
        "Plataforma", "senior → principal", "09:113,118,120;29:354,358,360;34:417,418,420;37:446,450,455",
        "Necesidad interna|Capacidad|Golden path|Adopción|Evolución",
        "Estandarizar o permitir excepción|ofrecer camino recomendado con escape explícito y soporte|adopción voluntaria más coste de excepción;Build o comprar plataforma|comparar diferenciación integración TCO y salida|experimento de onboarding y análisis económico;API o portal|diseñar capacidad estable antes que interfaz vistosa|tiempo hasta primer éxito y consumo automatizado",
        "Tiempo hasta primer despliegue|fricción desde repositorio nuevo hasta entorno útil|ensayar sólo con expertos;Adopción activa|equipos que usan y conservan la capacidad|contar repos creados;Carga cognitiva percibida|decisiones y conocimiento exigidos al consumidor|reducir opciones ocultando fallos",
        "Golden path falla y bloquea decenas de equipos|una actualización central rompe un supuesto no versionado|identificar contrato plantilla versión dependencia blast radius y salida|pausar rollout revertir ofrecer bypass seguro y añadir compatibilidad",
        "Plataforma interna como producto|convertir una necesidad repetida en autoservicio medido y versionado|API plantilla portal documentación SLO telemetría feedback modelo de soporte y deprecación",
        "KUBERNETES|DORA|SWEBOK", "developer-experience-engineer.md|devops-engineer.md|technical-leadership.md",
    ),
    "developer-experience-engineer.md": profile(
        "Plataforma", "semi-senior → principal", "08:97,104,106;09:113,118,120;34:409,417,418;37:446,448,455",
        "Fricción|Hipótesis|Herramienta|Feedback|Adopción",
        "Automatizar o enseñar|eliminar trabajo accidental sin ocultar modelos que se deben comprender|observación de onboarding y soporte;Velocidad o comprensión|acortar feedback conservando diagnóstico accionable|tiempo hasta causa no sólo hasta rojo;Uniformidad o autonomía|estandarizar interfaces y seguridad dejando decisiones de dominio|encuesta cualitativa más datos de uso",
        "Tiempo hasta primer cambio|capacidad de contribuir con contexto mínimo|medir sólo clon a build;Tiempo de feedback|duración hasta señal accionable en edición y CI|hacer checks rápidos pero inútiles;Interrupciones de soporte|fricción no resuelta por autoservicio y documentación|convertir menos tickets en objetivo aislado",
        "Una plantilla acelera el inicio pero produce servicios imposibles de depurar|el camino feliz omitió telemetría y límites operativos|observar uso real configuración errores feedback y handoff|corregir golden path migrar consumidores y medir comprensión",
        "Experiencia de desarrollo medible|reducir una fricción real desde investigación hasta adopción sostenible|journey map baseline prototipo herramienta documentación experimento métricas SPACE/DORA con límites",
        "DORA|DEVCONTAINERS|SWEBOK", "platform-engineer.md|technical-writer.md|engineering-manager.md",
    ),
    "security-engineer.md": profile(
        "Seguridad", "semi-senior → principal", "20:245,249,251;32:385,387,392;33:399,400,406;35:422,428,430",
        "Activo|Amenaza|Control|Prueba|Respuesta",
        "Prevenir o detectar|combinar controles según coste evasión y recuperación|prueba negativa más señal operativa;Bloquear o advertir|graduar por explotabilidad impacto confianza y salida|falsos positivos y excepciones que caducan;Secreto o identidad federada|reducir material de larga vida y blast radius|sesión efímera con mínimo privilegio",
        "Riesgo residual por amenaza|exposición después de controles y supuestos|contar vulnerabilidades sin contexto;Tiempo de contención|capacidad de revocar aislar y limitar daño|cerrar ticket sin verificar alcance;Cobertura de controles probados|defensas que realmente detectan o impiden abuso|contar herramientas instaladas",
        "Dependencia comprometida entra por un build legítimo|la firma confirma origen interno pero no integridad de la cadena previa|rastrear lockfile provenance builder SBOM permisos y consumidores|aislar artefacto revocar credenciales identificar alcance reconstruir y comunicar",
        "Producto con seguridad verificable|conectar amenazas con controles pruebas telemetría y respuesta|threat model requisitos controles negativos SBOM procedencia dashboard runbook y riesgo aceptado",
        "NISTSSDF|SLSA|ACMETHICS", "compliance-engineer.md|build-release-engineer.md|cloud-engineer.md",
    ),
    "compliance-engineer.md": profile(
        "Gobierno", "semi-senior → principal", "12:151,152,153;23:283,287,288;32:391,394,396;37:450,451,452",
        "Obligación|Requisito|Control|Prueba|Evidencia",
        "Control común o específico|reutilizar capacidad cuando la obligación y riesgo coinciden|matriz de trazabilidad y brecha explícita;Evidencia continua o puntual|automatizar recolección sin perder contexto y custodia|muestra reproducible con propietario;Cumplir o reducir riesgo|distinguir obligación legal criterio auditor y decisión técnica|opinión legal identificada y límite documentado",
        "Controles con evidencia vigente|implementaciones demostrables durante la ventana auditada|contar políticas aprobadas;Hallazgos reincidentes|causas que reaparecen entre auditorías|cerrar por documentación;Tiempo de obtención|capacidad de producir evidencia sin operación heroica|automatizar datos irrelevantes",
        "Auditor solicita prueba y el dashboard actual no demuestra el periodo|la organización confunde estado presente con evidencia histórica|rastrear obligación población control frecuencia fuente custodia y excepción|reconstruir muestra declarar límite corregir retención y probar extracción",
        "Paquete de cumplimiento trazable|traducir una obligación acotada hasta implementación prueba y evidencia revisable|mapa normativo requisitos controles owners pruebas evidencias excepciones y memo de límites",
        "ISO29148|NISTSSDF|ACMETHICS", "security-engineer.md|requirements-engineer.md|cto.md",
    ),
    "finops-engineer.md": profile(
        "Economía", "semi-senior → principal", "11:134,140,144;29:349,356,357;31:376,380,384;37:450,451,453",
        "Valor|Consumo|Asignación|Decisión|Seguimiento",
        "Ahorro o resiliencia|reducir desperdicio sin erosionar SLO ni opciones de recuperación|coste unitario más riesgo;Reservar o mantener elasticidad|comparar demanda incertidumbre compromiso y salida|escenarios de sensibilidad;Showback o chargeback|elegir incentivo que mejora decisiones sin castigar equipos|calidad de etiquetas y comportamiento observado",
        "Costo por unidad útil|gasto asociado a transacción cliente o capacidad|usar coste total sin denominador;Cobertura de asignación|consumo atribuible a propietario y producto|forzar etiquetas sin corregir shared cost;Forecast y desviación|capacidad de anticipar demanda y explicar cambio|premiar exactitud falsa",
        "Factura sube mientras el tráfico permanece estable|un cambio de arquitectura altera transferencia retención o unidad de cómputo|descomponer precio uso volumen compromiso y resultado|contener anomalía preservar servicio y presentar opciones con sensibilidad",
        "Caso económico operable|vincular telemetría técnica con coste valor riesgo y decisión reversible|modelo unitario dashboard forecast anomalías alternativas ADR y plan de seguimiento",
        "GSF|DORA|ISO25010", "cloud-engineer.md|technical-product-engineer.md|cto.md",
    ),
    "green-software-engineer.md": profile(
        "Sostenibilidad", "semi-senior → lead", "01:18,22,24;11:134,139,140;29:352,356,359;31:375,376,377",
        "Unidad funcional|Energía|Carbono|Cambio|Rebote",
        "Eficiencia o desplazamiento temporal|comparar energía carbono intensidad y deadline|SCI con frontera y datos declarados;Menos cómputo o mejor experiencia|proteger resultado útil accesibilidad y confiabilidad|presupuesto por tarea;Optimizar o retirar|considerar embodied carbon vida útil migración y datos retenidos|análisis de ciclo y plan de salida",
        "SCI por unidad funcional|emisiones asociadas a una tarea definida|cambiar frontera para mejorar cifra;Energía por operación|consumo físico o estimado con método declarado|convertir CPU directamente a carbono;Efecto rebote|demanda adicional causada por menor coste|declarar ahorro sin observar volumen",
        "Optimización reduce coste unitario pero aumenta consumo total|la capacidad liberada incentiva más frecuencia o retención|comparar unidad funcional demanda intensidad región y ventana|ajustar producto presupuesto y scheduling y reportar efecto neto",
        "Mejora sostenible basada en evidencia|medir una carga definir frontera reducir recursos y explicar trade-offs|baseline SCI experimento rendimiento coste calidad efecto rebote y recomendación",
        "GSF|ISO25010|ACMETHICS", "performance-engineer.md|finops-engineer.md|cloud-engineer.md",
    ),
    "technical-writer.md": profile(
        "Conocimiento", "junior → principal", "13:157,163,167;17:205,206,215;35:427,428,429;39:469,473,477",
        "Audiencia|Tarea|Contenido|Prueba|Mantenimiento",
        "Tutorial o referencia|elegir forma por necesidad y experiencia previa|prueba de tarea con persona objetivo;Precisión o descubribilidad|preservar exactitud sin esconder la respuesta|búsqueda y éxito de tarea;Documento o fuente ejecutable|derivar cuando sea posible y declarar ownership del resto|drift check y fecha de revisión",
        "Éxito de tarea documental|persona completa operación sin conocimiento tácito|medir visitas;Tiempo hasta primera respuesta|facilidad para encontrar y aplicar información correcta|optimizar SEO sin resolución;Drift detectado|diferencias entre producto contrato y documentación|contar cambios de palabras",
        "Runbook indica una acción que ya no existe|el sistema cambió pero el documento no tiene owner ni prueba|reproducir tarea comparar interfaz historial fuente y audiencia|corregir bloquear deriva y documentar límite y revisión",
        "Portal técnico probado por usuarios|convertir conocimiento disperso en tutorial how-to referencia explicación y operación coherentes|mapa de audiencia arquitectura de información docs-as-code pruebas de tareas búsqueda y política de vigencia",
        "DIATAXIS|OPENAPI|SWEBOK", "developer-experience-engineer.md|api-engineer.md|observability-engineer.md",
    ),
    "open-source-innersource-engineer.md": profile(
        "Colaboración", "semi-senior → principal", "09:110,117,119;16:196,199,200;33:399,400,406;37:446,448,452",
        "Comunidad|Contribución|Revisión|Release|Sostenibilidad",
        "Apertura o control|definir decisiones transparentes y límites de seguridad|governance y log de decisiones;Velocidad o mantenedor sostenible|reducir cola con ownership documentación y automatización|tiempo de revisión más carga humana;Dependencia o fork|comparar influencia upstream urgencia y coste de mantener divergencia|plan de contribución y salida",
        "Tiempo de primera contribución|fricción desde intención hasta cambio aceptable|medir sólo PR abierto;Bus factor|concentración de conocimiento y permisos críticos|contar contribuidores ocasionales;Carga de mantenedores|revisión soporte release y seguridad por persona|premiar volumen de issues cerrados",
        "Paquete comprometido exige coordinar usuarios y mantenedores|no existe inventario claro de versiones afectadas ni canal de divulgación|rastrear governance owners SBOM releases consumidores y embargo|contener publicar fix coordinar aviso y revisar proceso",
        "Proyecto abierto sostenible|diseñar contribución ownership release vulnerabilidades y sucesión|CONTRIBUTING governance CODEOWNERS plantillas release firmado disclosure métricas y plan de continuidad",
        "GIT|GITHUB|SPDX", "technical-writer.md|build-release-engineer.md|technical-leadership.md",
    ),
    "legacy-modernization-engineer.md": profile(
        "Evolución", "senior → principal", "08:105,107,108;24:294,295,298;36:434,435,444;37:450,451,453",
        "Descubrir|Caracterizar|Aislar|Migrar|Retirar",
        "Reescribir o evolucionar|comparar valor riesgo coexistencia y conocimiento perdido|caso económico más prueba de caracterización;Strangler o branch by abstraction|elegir frontera según tráfico datos y ciclo de despliegue|migración reversible;Compatibilidad o limpieza inmediata|pagar coexistencia temporal para reducir riesgo|telemetría de consumidores y criterio de retiro",
        "Cobertura de comportamiento crítico|rutas legacy protegidas por caracterización|usar cobertura de líneas;Porcentaje de tráfico migrado|adopción real de la nueva ruta con calidad equivalente|mover tráfico sin datos;Tiempo de rollback|capacidad de volver ante divergencia|confiar en backup no ensayado",
        "Nueva implementación produce totales distintos sin especificación confiable|el comportamiento real incluye reglas implícitas y datos históricos|comparar salidas fixtures trazas decisiones y excepciones de negocio|detener migración preservar ambos caminos y convertir diferencia en requisito",
        "Migración incremental reversible|comprender un sistema ajeno estabilizarlo y retirar una capacidad sin big bang|mapa dependencias caracterización ADR strangler migración datos observabilidad rollout rollback y decommission",
        "SWEBOK|ISO25010|SEMVER", "software-architect.md|database-reliability-engineer.md|technical-leadership.md",
    ),
    "software-architect.md": profile(
        "Diseño sistémico", "senior → principal", "12:147,151,154;25:301,303,309;28:341,342,346;37:446,450,455",
        "Contexto|Driver|Alternativas|Decisión|Fitness",
        "Modular monolith o microservicios|derivar límites de autonomía escala y fallo no de organigrama ideal|escenarios de calidad y coste operacional;Consistencia o disponibilidad|asignar garantías por flujo y daño de divergencia|modelo de fallos más experimento;Estándar o excepción|crear coherencia donde reduce coste y salida donde el contexto difiere|fitness functions y revisión periódica",
        "Drivers con evidencia|decisiones conectadas a requisitos y escenarios|contar ADR;Fitness functions activas|propiedades arquitectónicas verificadas continuamente|convertir toda preferencia en gate;Costo de cambio transversal|equipos y componentes afectados por una evolución|premiar uniformidad",
        "Un servicio crítico se degrada por una dependencia aparentemente auxiliar|el diagrama estático no representa runtime colas timeouts ni ownership|reconstruir vistas trazas contratos despliegue y escenarios de calidad|contener rediseñar límite y registrar decisión con condición de revisión",
        "Arquitectura defendible y evolutiva|comparar alternativas contra atributos de calidad operación y organización|contexto C4 escenarios ADR prototipo de riesgo fitness functions threat model coste y roadmap",
        "C4|ISO25010|SWEBOK", "solutions-architect.md|technical-leadership.md|legacy-modernization-engineer.md",
    ),
    "solutions-architect.md": profile(
        "Diseño de soluciones", "senior → principal", "10:121,126,128;25:301,302,309;29:349,357,360;37:450,451,455",
        "Contexto|Capacidad|Integración|Transición|Adopción",
        "Build buy o partner|comparar diferenciación TCO dependencia y estrategia de salida|prueba de concepto más matriz económica;Producto o plataforma|definir consumidor ownership y operación antes de la tecnología|service blueprint y RACI;Migración directa o coexistencia|reducir riesgo mediante etapas observables|plan de transición con rollback",
        "Tiempo hasta valor|duración desde decisión hasta uso efectivo|medir firma de contrato;Costo total por escenario|construcción integración operación cambio y salida|comparar sólo licencias;Riesgos abiertos|supuestos sin owner evidencia o fecha de revisión|convertir todo en semáforo verde",
        "Proveedor cumple demo pero falla al integrar identidad y datos reales|la evaluación omitió restricciones no funcionales y modelo operativo|revisar contrato capacidades límites SLAs datos seguridad soporte y salida|contener alcance validar integración y renegociar decisión con evidencia",
        "Solución transitable de contexto a operación|resolver una necesidad combinando componentes propios y externos con salida explícita|mapa de capacidades opciones PoC arquitectura integración TCO riesgos plan de transición y aceptación",
        "ISO25010|OPENAPI|C4", "software-architect.md|technical-product-engineer.md|cloud-engineer.md",
    ),
    "technical-product-engineer.md": profile(
        "Producto técnico", "semi-senior → principal", "10:121,124,132;11:134,138,144;12:146,149,154;38:461,465,468",
        "Problema|Hipótesis|Experimento|Entrega|Aprendizaje",
        "Descubrir o construir|reducir primero la incertidumbre que puede invalidar inversión|evidencia de usuario y criterio de no éxito;Métrica o narrativa|combinar señal cuantitativa con mecanismo causal y contexto|guardrails y análisis de sesgo;Prototipo o producto|declarar qué riesgo prueba cada artefacto y qué no|decisión posterior explícita",
        "Outcome de usuario|cambio de capacidad o resultado no actividad interna|celebrar features entregadas;Tiempo hasta aprendizaje|velocidad para invalidar una suposición importante|hacer experimentos sin decisión;Costo de demora|valor perdido y opciones cerradas por secuencia|inventar precisión monetaria",
        "Una función aumenta uso pero empeora el resultado del cliente|la métrica principal captura actividad y omite guardrail|revisar hipótesis segmento instrumentación causalidad daño y alternativas|pausar rollout proteger usuarios y rediseñar experimento",
        "Decisión de producto técnico|pasar de problema ambiguo a experimento y entrega evaluable|research brief mapa de supuestos prototipo métricas guardrails factibilidad TCO y memo de decisión",
        "ISO29148|NISTAI|ACMETHICS", "requirements-engineer.md|solutions-architect.md|finops-engineer.md",
    ),
    "technical-leadership.md": profile(
        "Liderazgo técnico", "senior → principal", "15:186,187,190;25:309,310,311;35:428,429,430;37:445,448,455",
        "Ambigüedad|Alineamiento|Decisión|Delegación|Aprendizaje",
        "Decidir o facilitar|usar autoridad técnica sólo cuando riesgo y tiempo lo requieren|decision record y participación adecuada;Consistencia o autonomía|definir principios interfaces y ownership sin microgestión|resultados entre equipos y excepciones;Deuda o entrega|hacer visible interés riesgo y oportunidad para secuenciar|opciones y criterio de revisión",
        "Decisiones reabiertas|claridad insuficiente de contexto autoridad o evidencia|evitar debate contando reuniones;Dependencias entre equipos|esperas y handoffs que bloquean outcomes|culpar velocidad individual;Crecimiento de referentes|personas que asumen decisiones con soporte decreciente|medir mentorías realizadas",
        "Dos equipos bloquean una migración por incentivos opuestos|cada uno optimiza su servicio y nadie responde por el flujo completo|mapear outcome dependencias riesgo autoridad alternativas y coste de espera|facilitar decisión asignar owners etapas y revisión sin imponer falsa unanimidad",
        "Programa técnico multiequipo|conducir una decisión transversal desde RFC hasta adopción y aprendizaje|contexto opciones ADR/RFC mapa de stakeholders plan incremental métricas riesgos mentoring y retrospectiva",
        "SWEBOK|DORA|ACMETHICS", "software-architect.md|engineering-manager.md|cto.md",
    ),
    "engineering-manager.md": profile(
        "Liderazgo de personas", "senior → dirección", "15:184,189,190;31:373,379,380;35:428,429,430;37:446,447,448",
        "Contexto|Equipo|Flujo|Entrega|Crecimiento",
        "Compromiso o forecast|comunicar rango riesgo y capacidad sin convertir incertidumbre en promesa|revisión de supuestos y flujo;Autonomía o coordinación|dar ownership claro con mecanismos de alineación|dependencias y decisiones escaladas;Rendimiento o sostenibilidad|proteger ritmo calidad guardia y aprendizaje|tendencias de salud y outcomes",
        "Throughput y cycle time|flujo del sistema no productividad individual|rankear personas;Carga de guardia|impacto operativo y distribución justa|normalizar heroísmo;Crecimiento y movilidad|capacidad asumida con feedback y oportunidades|contar promociones como única señal",
        "Equipo cumple fechas a costa de incidentes y desgaste|los incentivos premian output y ocultan calidad capacidad y toil|revisar demanda WIP ownership guardia deuda feedback y seguridad psicológica|reducir carga renegociar compromiso reparar sistema y aprender sin culpabilizar",
        "Sistema de equipo sostenible|mejorar un flujo real sin sacrificar calidad personas ni operación|baseline de flujo mapa de carga acuerdos ownership plan de capacidad feedback y retrospectiva",
        "KANBAN|DORA|ACMETHICS", "technical-leadership.md|developer-experience-engineer.md|cto.md",
    ),
    "cto.md": profile(
        "Dirección", "dirección ejecutiva", "11:134,141,144;25:301,309,310;36:441,442,444;37:450,451,453",
        "Estrategia|Portafolio|Organización|Riesgo|Renovación",
        "Invertir construir o comprar|asignar capital por capacidad diferenciación riesgo y opción de salida|caso económico con revisión;Centralizar o federar tecnología|alinear plataformas estándares y autonomía a estrategia|coste de coordinación y ownership;Explotar o modernizar|equilibrar continuidad deuda talento y oportunidad|roadmap financiable con hitos reversibles",
        "Valor y riesgo del portafolio|outcomes opciones exposición y concentración|sumar proyectos verdes;Costo total de capacidades|construcción operación cambio proveedores y retiro|mirar presupuesto anual;Resiliencia organizacional|sucesión bus factor y respuesta a crisis|medir headcount",
        "Incidente revela dependencia estratégica de un proveedor sin salida|la organización optimizó corto plazo y perdió conocimiento y control|reconstruir contrato arquitectura datos costes riesgo regulatorio y alternativas|estabilizar comunicar decidir horizonte de salida y financiar capacidades críticas",
        "Estrategia tecnológica defendible|conectar estrategia de negocio con capacidades inversiones organización riesgos y aprendizaje|mapa de capacidades portfolio TCO escenarios build-buy roadmap operating model indicadores y memo al directorio",
        "SWEBOK|ISO25010|ACMETHICS", "technical-leadership.md|software-architect.md|engineering-manager.md",
    ),
    "ai-augmented-software-engineer.md": profile(
        "Ingeniería con IA", "junior → principal", "13:165,166,168;30:365,366,371;38:457,465,468;39:473,477,479",
        "Intención|Contexto|Propuesta IA|Verificación|Revisión humana",
        "Automatizar o asistir|ceder ejecución sólo cuando autoridad pruebas y reversión son adecuadas|eval más log de herramientas;Contexto amplio o mínimo|aportar evidencia suficiente sin filtrar secretos ni saturar atención|prueba de recuperación y coste;Aceptar o regenerar|diagnosticar causa y cambiar especificación herramienta o modelo|regresión determinista no preferencia estética",
        "Tasa de aceptación verificada|propuestas que pasan revisión y sistema sin regresión|contar sugerencias aceptadas;Costo por cambio válido|tokens latencia revisión y retrabajo por outcome|comparar precio de llamada;Regresiones asistidas|defectos introducidos o no detectados por flujo IA|atribuir éxito al agente",
        "Agente declara terminado pero inventa una API y tests que no ejercen el fallo|la señal de éxito proviene del mismo contexto que generó la solución|revisar diff dependencias documentación oficial oráculos permisos y pruebas externas|detener revertir corregir SPEC y añadir eval que capture el patrón",
        "Cambio asistido auditable|comparar flujo manual asistido y agentic sobre una mejora real|SPEC contexto prompts tool log diff pruebas eval seguridad revisión humana coste y retrospectiva",
        "NISTAI|MCP|NISTSSDF", "software-engineer.md|ai-systems-engineer.md|technical-leadership.md",
    ),
    "ai-systems-engineer.md": profile(
        "Sistemas con IA", "semi-senior → principal", "11:137,138,139;23:279,287,288;38:457,465,466;39:473,475,478",
        "Tarea|Datos|Modelo|Guardrail|Operación",
        "Modelo grande o pequeño|comparar calidad latencia coste privacidad y control|eval por segmento y presupuesto;Prompt o ajuste|elegir intervención por estabilidad datos y mantenimiento|baseline versionado y conjunto de regresión;Responder o abstener|definir incertidumbre daño fallback y escalamiento humano|pruebas de negativa y recuperación",
        "Calidad por segmento|resultado útil y daño para grupos y casos distintos|publicar un promedio global;Costo y latencia por tarea|recursos desde entrada hasta decisión útil|medir sólo inferencia;Tasa de fallback|veces que el sistema se abstiene deriva o escala|tratar toda abstención como fracaso",
        "Modelo responde con seguridad aparente pero dato falso en flujo crítico|el sistema carece de grounding cita umbral o fallback adecuado|rastrear entrada contexto retrieval modelo versión salida guardrail y decisión|contener bajar autoridad activar fallback revisar dataset y añadir eval adversarial",
        "Capacidad de IA operable y reversible|integrar un modelo con evaluación guardrails observabilidad privacidad y fallback|dataset card evals baseline contrato de modelo threat model trazas control humano y runbook",
        "NISTAI|MCP|ISO25010", "ai-augmented-software-engineer.md|data-engineer.md|security-engineer.md",
    ),
}
